MicrosoftDocs/Contribute

Contribute/additional-resources.md
Contribute/breadcrumb/toc.yml
Contribute/docfx.json
Contribute/full-workflow.md
Contribute/get-started-setup-github.md
Contribute/get-started-setup-local.md
Contribute/get-started-setup-tools.md
Contribute/git-github-fundamentals.md
Contribute/how-to-contribute.md
Contribute/how-to-write-links.md
Contribute/how-to-write-use-markdown.md
Contribute/how-to-write-workflows-major.md
Contribute/index.md
Contribute/light-workflow.md

* Making titles better, 
* Putting title prefix into config instead of each file, and 
* Switching to GitHub issues

Hopefully final updates for v1 of Contributor Guide

---

Contribute/TOC.md
Contribute/how-to-write-docs-auth-pack.md

Adding external facing documentation for the Docs Authoring Pack for VS Code.

Docs Authoring Pack

---

Contribute/style-quick-start.md

Fixed #25
Updated links to the existing localization guide, and include a link to the new style guide on docs.microsoft.com
/cc @mairaw

Update localization links

---

Contribute/how-to-write-links.md

Fixes MicrosoftDocs/feedback#375
/cc @dend

discourage the user of `~/` links.

---

.openpublishing.publish.config.json

edits should start in master, and be reviewed before going live.
/cc @arob98

change target edit branch from "live" to "master"

---

Contribute/style-quick-start.md

Minor editing to remove future tense and be more concise.
Cherry pick for clean version of #50

Minor edits near the top of the article

---

Contribute/index.md

suggesting a couple of edits to clarify possibilities and WW impact

clarifications for WW

---

Contribute/how-to-write-links.md

Hello, @DuncanmaMSFT, @BillWagner, @JasonWHowell, @Jemash,
Translator has reported possible source content issue. 
Description of the source issue: Example URL should be escaped in order to avoid creating a link
Please review and merge the suggested proposed file change to avoid this error. If you make related fix in another PR, then share your PR number, so we can confirm and close this PR.
Many thanks in advance.

C38408: Extra hyperlink at line 159

---

ThirdPartyNotices.md

Closes https://github.com/MicrosoftDocs/Contribute/issues/93

ThirdPartyNotices.txt --> ThirdPartyNotices.md

---

Contribute/get-started-setup-local.md

Reads much better with "the" added.

Added word: the

---

Contribute/how-to-write-use-markdown.md

Adjusted spacing of ordered list example for CommonMark compliance.

Adjusted spacing of ordered list example

---

Contribute/index.md

Corrected spelling of available

Fixed typo mistake

---

Contribute/get-started-setup-github.md

* "affilations" should be "affiliations"
* "activitives" should be "activities"
Changes for [this link](https://docs.microsoft.com/en-us/contribute/get-started-setup-github#set-up-your-github-account).

Correct typos in github setup

---

Contribute/how-to-write-docs-auth-pack.md

Removed reference to freshness date which isn't a common phrase I have seen before and put the less ambiguous "last modified date" instead.

Change language use

---

Contribute/index.md

I believe this note was missing a definite article at lines 35-36. On line 62, available was misspelled.

fixed grammar and spelling

---

Contribute/get-started-setup-github.md

It's quite tricky to read as it stands so I have suggested an alternative.
The good news is, you have to do most steps only one time => The good news is, you usually only have to perform these steps once.

Alter style of sentence

---

Contribute/git-github-fundamentals.md

Added full-stops to mirror rest of document.

Missing punctuation

---

Contribute/TOC.md
Contribute/get-started-setup-github.md
Contribute/get-started-setup-local.md
Contribute/index.md

Fixed some typos and capitalization in 4 files

Fix various typos and H1 headings in TOC.md

---

Contribute/get-started-setup-local.md

I'm a first timer hoping to get some experience. Hope this PR is reasonable. I felt that a link was required at that particular position. 
Thanks

Change URL to link

---

Contribute/how-to-write-links.md

In order to increase consistency.

how-to-write-links.md: Add inline code

---

Contribute/how-to-write-links.md

Explaining selectors. Formatting code blocks as markdown language.

Fixes MicrosoftDocs/Contribute#126

---

ThirdPartyNotices.md

corrected text

---

Contribute/dotnet-contribute.md

Hello, @BillWagner,
Translator has reported possible source content issue. 
Please review and merge the suggested proposed file change to avoid this error. If you make related fix in another PR, then share your PR number, so we can confirm and close this PR.
Many thanks in advance.

M32698: Missing verb

---

Contribute/dotnet-contribute-process.md

Hello, @BillWagner,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

C52200: Adding line breaks

---

Contribute/dotnet-style-guide.md

Fixes https://github.com/dotnet/docs/issues/9376

fix syntax for markdig

---

Contribute/index.md

Adding information regarding Edit button missing.
Updating the steps to be numbered

Fixes MicrosoftDocs/Contribute#198

---

Contribute/index.md

Publishing today's changes
* Fixes MicrosoftDocs/Contribute#198
Adding information regarding Edit button missing.
Updating the steps to be numbered
* Update index.md
Updating formatting and text.

Publishing to live

---

Contribute/includes/contribute-how-to-pull-requests-apex-automation.md

* Removed extra #sign-off line from review table
* Fixes MicrosoftDocs/Contribute#250
* Update contribute-how-to-pull-requests-apex-automation.md

includes/contribute-how-to-pull-requests-apex-automation.md (#252)

---

Contribute/get-started-setup-local.md

Updated line 12, was missing a preposition 'on' - You run these one-time setup activities to get started on contributing:

Updated get-started-setup-local.md

---

.openpublishing.publish.config.json
Contribute/get-started-setup-local.md
Contribute/validation-reference/ms-author-missing.md

Adding the PDF download link.
A couple of other small edits.

Publishing master to live

---

Contribute/validation-reference/includes/suggestion-note.md

adding correct ms.topic

---

Contribute/how-to-write-use-markdown.md
Contribute/validation-reference/h1-in-moniker.md
Contribute/validation-reference/multiple-h1s.md

Same like with https://github.com/dotnet/docs/pull/15471

Add supported identifier

---

Contribute/TOC.yml

Add entry for style guide

---

Contribute/code-in-docs.md

Added command prompt to the "Fenced code blocks" list

Added command prompt to the "Fenced code blocks" list

---

Contribute/docs-authoring/image-compression.md

Hi @Jim-Parker,
This fixes: https://github.com/MicrosoftDocs/Contribute/pull/367#issuecomment-594964177. When does this get published?

Remove invalid URL in image compression feature doc.

---

.openpublishing.redirection.json

@Jim-Parker Please add these redirections.

Add redirections for moved dotnet content

---

Contribute/dotnet/dotnet-contribute.md

Contributes to https://github.com/MicrosoftDocs/Contribute/issues/384

Copy Int'l content section from repo copy of the doc

---

Contribute/index.md

Line 37: "login" should be 2 words
Line 66: Replaced "So" with "Thus," 
Alternatively, could be: "In this way," or "In this manner," or "As a result,"

2 minor fixes

---

Contribute/how-to-write-links.md

Fix backticks in generic type

---

Contribute/dotnet/dotnet-contribute.md

Reverts MicrosoftDocs/Contribute#411

Revert "Update contrib guide"

---

Contribute/get-started-setup-local.md

https://docs.microsoft.com/en-us/contribute/get-started-setup-local

Typo "git repository"→"Git repository"

---

Contribute/TOC.yml
Contribute/dotnet/labels-projects.md

Added milestones to GitHub workflow details article for .NET docs team
✔️ [Labels, projects, and milestones roadmap](https://review.docs.microsoft.com/en-us/contribute/dotnet/labels-projects?branch=pr-en-us-421)

Added milestones to GitHub workflow details article for .NET docs team

---

Contribute/dotnet/dotnet-voice-tone.md

Minor clarifications

---

Contribute/dotnet/dotnet-style-guide.md

Link to the code-in-docs article for syntax info

---

Contribute/dotnet/labels-projects.md

[Internal review URL](https://review.docs.microsoft.com/en-us/contribute/dotnet/labels-projects?branch=pr-en-us-447#priority)
@gewarren @BillWagner please review

Update priority descriptions

---

Contribute/how-to-write-workflows-major.md

#445 added command to update fork with changes from upstream

#445 added command to update fork with changes from upstream

---

Contribute/TOC.yml
Contribute/dotnet/net-core-5-naming.md

@BillWagner @IEvangelist Please review

.NET 5 and .NET Core naming doc

---

.openpublishing.publish.config.json

Updated the json to enable CRR

Updated json for CRR

---

Contribute/get-started-setup-tools.md

Updated Tools

---

Contribute/markdown-reference.md

Add comments info and update based on update in private repo

Add comments text

---

Contribute/markdown-reference.md

Updating to match the indentation guidance that was added to the internal Markdown article.

Add indentation guidance

---

Contribute/index.md

Step one contained two nearly identical sentences.

Remove duplicate sentence

---

Contribute/index.md

- Capitalized "Contributor Guide" to be consistent across doc (could also make other instances lower-case instead)
- Changed a bold "Some" to italics to be consistent with bold/italics use across doc
- Updated "Propose file change" to "Propose changes" to match screenshot and actual button text
- Made several instances of "change" plural
- Capitalized first word "Create" in image alt-text to be consistent with other images
- Miscellaneous comma additions and removals

Made some small grammar and consistency edits.

---

.openpublishing.publish.config.json

Thanks for contributing to the [docs.microsoft.com contributor guide](https://docs.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.
- Write to the PR reviewer in the PR comments: `@carlyrevier, @jehchow`

update branch name for cross repo reference

---

Contribute/markdown-reference.md

update language codes for Markdown blocks

---

Contribute/docfx.json

Thanks for contributing to the [docs.microsoft.com contributor guide](https://docs.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.
- Write to the PR reviewer in the PR comments: `@carlyrevier, @jehchow`

Adding name to exclude setting

---

Contribute/dotnet/dotnet-contribute.md

Clarify that sample code should be contained in a snippets project, not included inline in the article.
Fixes #616
Thanks for contributing to the [docs.microsoft.com contributor guide](https://docs.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.
- Write to the PR reviewer in the PR comments: `@carlyrevier, @jehchow`

Add policy to use embedded code from snippets

---

Contribute/code-in-docs.md

Fixes #634 
@KathleenDollard please review.

Add an example showing link vs. code style

---

Contribute/code-in-docs.md

Fixes #635
@KathleenDollard please review.

Mention screenshots in first sentence

---

Contribute/dotnet/net-core-5-naming.md

Add note about .NET Framework

---

Contribute/additional-resources.md
Contribute/code-in-docs.md
Contribute/docs-authoring/sort-redirects.md
Contribute/dotnet/dotnet-contribute.md
Contribute/get-started-setup-github.md
Contribute/get-started-setup-local.md
Contribute/git-github-fundamentals.md
Contribute/hacktoberfest.md

**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

[BULK] DocuTune - Fix build validation issues: docs-link-absolute (part 1)

---

Contribute/style-quick-start.md
Contribute/text-formatting-guidelines.md
README.md

**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

[BULK] DocuTune - Fix build validation issues: docs-link-absolute (part 3)

---

Contribute/TOC.yml
Contribute/hacktoberfest.md

Adding Hacktoberfest article back to the TOC for 2022 season.

Adding Hacktoberfest article for 2022

---

.github/ISSUE_TEMPLATE/general-issue-template.md
Contribute/additional-resources.md
Contribute/code-in-docs.md
Contribute/docs-authoring/sort-redirects.md
Contribute/dotnet/dotnet-contribute.md
Contribute/get-started-setup-github.md
Contribute/get-started-setup-local.md
Contribute/git-github-fundamentals.md
Contribute/hacktoberfest.md
Contribute/how-to-write-docs-auth-pack.md
Contribute/how-to-write-links.md
Contribute/index.md
Contribute/markdown-reference.md
README.md

**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

[BULK UPDATE] DocuTune - Rebranding

---

.github/ISSUE_TEMPLATE/general-issue-template.md
.github/PULL_REQUEST_TEMPLATE.md
Contribute/TOC.yml
Contribute/architecture-center/aac-contribute.md
Contribute/architecture-center/guide-templates.md
Contribute/architecture-center/sample-solution-templates.md
Contribute/git-github-fundamentals.md
Contribute/hacktoberfest.md
Contribute/how-to-write-docs-auth-pack.md
Contribute/how-to-write-links.md
Contribute/how-to-write-workflows-major.md
Contribute/index.md
Contribute/markdown-reference.md
Contribute/metadata.md
Contribute/style-quick-start.md
Contribute/text-formatting-guidelines.md

**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

[BULK] DocuTune - Rebranding

---

Contribute/docs-authoring/includes/image-extension.md

Updating one "Docs Images" reference to "Learn Images".

Learn Images update

---

Contribute/docs-authoring/includes/image-extension.md
Contribute/hacktoberfest.md

Merge main to live for October 3, 2022.

Merge main to live - 10/3/22

---

Contribute/docs-authoring/jupyter-notebooks.md

Add a section detailing how to access the notebook functions.  Reviewed rest of article for freshness and updated ms.date.

Add access info

---

Contribute/includes/contribute-how-to-pull-requests-apex-automation.md

**Updated:** https://learn.microsoft.com/en-us/contribute/how-to-write-workflows-major
with **PR comments/commands** 
(Story 706758)

added PR comments/commands to <how-to-write-workflows-major> article

---

Contribute/architecture-center/aac-contribute.md
Contribute/architecture-center/guide-templates.md
Contribute/architecture-center/sample-solution-templates.md
Contribute/architecture-center/solution-idea-templates.md

Updating author information for AAC articles. cc @martinekuan

Updating AAC author information

---

Contribute/how-to-write-links.md

Fix xref lookup URLs

---

README.md

Malformed URL for Microsoft Learn documentation contributor guide leading to https://github.com/MicrosoftDocs/Contribute/blob/main/contribute and Page Not Found error.
Thanks for contributing to the [Microsoft Learn documentation contributor guide](https://learn.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.
- Write to the PR …

Fixed URL Error

---

.github/workflows/check-build-warnings.yml
README.md

Merging main to live for 3/20/23.

Merge main to live 3/20/23

---

Contribute/how-to-write-docs-auth-pack.md

Merging main to live.
---
| 📄 File | 🔗 Preview link |
|:--|:--|
| [Contribute/how-to-write-docs-auth-pack.md](https://github.com/MicrosoftDocs/Contribute/blob/efe11e1955ed2ea48316d8e0bc7410aea3e734d7/Contribute/how-to-write-docs-auth-pack.md) | [Contribute/how-to-write-docs-auth-pack](https://review.learn.microsoft.com/en-us/contribute/how-to-write-docs-auth-pack?branch=pr-en-us-759) |

Merge main to live - March 30, 2023

---

Contribute/index.yml

Update Collections link w/URL to new Collections article.

Fix Collections link

---

Contribute/index.yml

Merging main to live for August 29, 2023.

Merge main to live - 8/29/23

---

Contribute/index.yml

Updated Q&A contribution text

---

Contribute/content/index.md

In this commit, the ‘What’s in it for me?’ section has been revised for better clarity and engagement. 
The changes highlight the benefits users receive when they contribute to Microsoft Learn. 
These include recognition of their contributions, enhancement of their tech passion, and portfolio building. 
The update also emphasizes the digital rewards some products offer. 
The aim is to encourage more users to contribute and enjoy the benefits.
- All PRs to this repository are manually reviewed and …

Modified the ‘What’s in it for me?’ section for clarity and engagement.

---

Contribute/content/TOC.yml
Contribute/content/seo-reference.md
Contribute/index.yml

This pull request includes changes related to improving the content and structure of the Contribute section. The most important changes include adding a new link titled "Making Your Content More Discoverable" and updating the TOC.yml file to include a new entry for "SEO reference".
Content and structure improvements:
* <a href="diffhunk://#diff-1c729de931c8cb01b93cfb130566a22f6e55b0668eeee47f88e466e9160ce442L84-R90">`Contribute/index.yml`</a>: Added a new link titled "Making Your Content More Discoverable" in the "sections" section of the file.
* <a href="diffhunk://#diff-5ce352959735b4cf444450610b0715e7821c2f47f0898dba7de8714c73ed7317R42-R44">`Contribute/content/TOC.yml`</a>: Added a new entry called "SEO reference" and updated the display names of "Format text" and "Links". <a …

Add SEO article

---

Contribute/content/how-to-write-quick-edits.md

Fixed some grammatical errors and Typos

---

Contribute/content/index.md

added more information about Microsoft Learn

---

Contribute/content/index.md

Update introduction line

---

Contribute/content/git-github-fundamentals.md

I have added simplified answers to frequently asked questions about Git and GitHub which will give users an easy to help materials to find their answers within no time.

Added the FAQs of Git & GitHub

---

Contribute/content/how-to-create-github-issues.md

Main to live push for March 14, 2024.

Main to live - March 14, 2024

---

CODEOWNERS
Contribute/content/how-to-write-overview.md

Merging main to live for 6/11/24 so codeowners can go live.

Main to live - 6/11/24

---

Contribute/content/architecture-center/aac-contribute.md

- Remove link to github issues and instead use UUF
- Be clear this is "Azure" patterns & practices, not any of the other PnP teams
- Replace martin with our new manager, Luke

[Update] Azure patterns & practices - Freshness pass

---

Contribute/content/how-to-write-quick-edits.md

Fixed "Edit pencil icon" name across the topic.

Fixed "Edit pencil icon" name across the topic.
