MicrosoftDocs/Contribute

- .openpublishing.publish.config.json
It's much more useful to see only the most recent build status on a PR than seeing the history of all messages from all builds on the PR.
/cc @DuncanmaMSFT
> turn off PR comments

- Contribute/additional-resources.md
- Contribute/docfx.json
- Contribute/get-started-setup-github.md
- Contribute/get-started-setup-local.md
- Contribute/get-started-setup-tools.md
- Contribute/git-github-fundamentals.md
- Contribute/how-to-write-docs-auth-pack.md
- Contribute/how-to-write-links.md
- Contribute/how-to-write-use-markdown.md
- Contribute/how-to-write-workflows-major.md
- Contribute/index.md
- Contribute/style-quick-start.md
This PR does the following:
1. add defaults in docfx.json for the following metadata: ms.prod, ms.technology, ms.custom,  author, ms.author, and manager.
2. Remove those items from *.md where the defaults are correct.
A future PR may change the defaults to a bot and an alias. Therefore, articles that did not have the old values for author or ms.author were not changed.
/cc @MonicaRush, @jasonh,  @mbradley, @BryanLa
> change default metadata

- Contribute/get-started-setup-tools.md
The current instructions are biased for Windows. This updates to include basic macOS and Linux pointers for git, including the fact that git is part of the Xcode Command Line Tools on macOS and will prompt for installation when you try to run git for the first time.
> Expand git instructions for Mac and Linux

- Contribute/style-quick-start.md
Also, deleted this guideline: Include the words "as follows" or "following" in any sentence that precedes a list or code snippet.
That guideline doesn't appear in the Microsoft Writing Style Guide (see [introductory text](https://docs.microsoft.com/en-us/style-guide/scannable-content/lists#introductory-text) and [following](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/f/following)). Even this page doesn't follow that guideline.
> Added a link to the Writing Style Guide

- Contribute/TOC.md
- Contribute/how-to-write-use-markdown.md
Updates to pull request #91 
reversal of previous sentence casing changes
coode -> code
Added link to: Docs.microsoft.com
Shorten acronym on second use: GitHub Flavored Markdown (GFM) -> GFM
Added "the" to: the additional linking syntax
> Updates to TOC.md and how-to-write-use-markdown.md

- Contribute/TOC.md
- Contribute/git-github-fundamentals.md
- Contribute/how-to-write-use-markdown.md
- Contribute/markdown-reference.md
Fixed Markdown examples for proper indenting. Added Markdown Reference article. The how to article references use of OPS extensions but does not show the syntax. The Markdown Reference article shows the syntax.
> fixed markdown examples and added OPS extensions

- Contribute/how-to-write-workflows-major.md
"Remote" was used in the plural in some sentences, in disagreement with the standard set by the section.
> corrected "remote" section for verb form agreement

- Contribute/index.md
Moved out a non-related paragraph out of the note alarm block. Also moved the figure directly under the paragraph that mentions it.
> Quick edits to existing documents: fixed note

- Contribute/additional-resources.md
Added "on Pluralsight" for the Git course from Code School because it has now merged in the Pluralsight platform. 
Code School has closed its website & the link mentioned here redirects to a different Git course and also need to be a member in order to do that course, which does mention that a person can sign up for a free trial.
Not sure if you either want to keep the same link or change it to other Git courses offered on Pluralsight by Code School that are free to use.
> Update in "Git source control section"

- Contribute/markdown-reference.md
Hello, @meganbradley,
Translator has reported possible source content issue. 
Description: Is the object for "standardized" missing? Or should this read "was standardized"? Please advise.
Please review and merge the suggested proposed file change to avoid this error. If you make related fix in another PR, then share your PR number, so we can confirm and close this PR.
Many thanks in advance.
> M32370: Word Missing?

- Contribute/how-to-write-use-markdown.md
"include" is not a noun. Updated to refer to 
- include file
- include files
- include as a verb
- include extensions
> Updated use of the word include

- Contribute/how-to-write-use-markdown.md
We are replacing the existing PowerApps entry that was unused with two new langauges: powerapps-dot and powerapps-comma.  There are two languages since we localize the formula language to be user friendly in regions that use "," (comma) as a decimal separator, consistent with what Excel does.  @DuncanmaMSFT has been helping us with setting this up and has reviewed this change.
> Update for PowerApps languages

- Contribute/how-to-write-use-markdown.md
We are replacing the existing PowerApps entry that was unused with two new langauges: powerapps-dot and powerapps-comma.  There are two languages since we localize the formula language to be user friendly in regions that use "," (comma) as a decimal separator, consistent with what Excel does.  @DuncanmaMSFT has been helping us with setting this up and has reviewed this change.
> Update for PowerApps languages (#167)

- Contribute/TOC.md
- Contribute/dotnet-pr-review.md
This was in the internal guide, but should be visible to our external contributors.
> move .NET PR review process to the external guide.

- Contribute/how-to-write-use-markdown.md
Adding  Docker > dockerfile and Kusto Query Language > kusto to the list of supported languages for code blocks. Reviewed this with Den.
> Fixes MicrosoftDocs/Contribute#179

- Contribute/docfx.json
Turning on searchScope for the external contributor guide (reverse of `hideScope: true` is false) after 48 hours (which was 10 months ago).  See Duncan's commit notes in: https://github.com/MicrosoftDocs/Contribute/commit/359449f4cc7068bfd682401c79c6e4f0bf6f9a05
May help resolve this issue: MicrosoftDocs/Contribute#129
> Turn on search scoped for external contribute guide

- Contribute/how-to-write-use-markdown.md
The paragraph about Markdown flavors is too technical for new users. If it's the second paragraph, it will scare them away. I moved it to the end of the article, with its own heading.
> Move the paragraph about flavors

- Contribute/get-started-setup-local.md
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: Extra space inside link is breaking link.
> C122697: removing extra space inside link syntax

- Contribute/how-to-write-use-markdown.md
Generally don't refer to OPS any more, where possible, as it is just the Docs publishing pipeline and doesn't need it's own brand (just makes things more confusing)
> Removing references to OPS

- Contribute/how-to-write-workflows-major.md
The contribute instructions seem to suggest users use Git Bash, and then even has a few examples, but then on the final page assumes they could be using any Git product and they should consult the manual.  Since we assume Git Bash up until now, I expanded upon the workflow to show how to checkout a branch, commit to that branch, and push it upstream.
> New Instructions for Git Bash Users

- Contribute/how-to-write-links.md
- Fixes #314 
- Explains 'docset'
- Relative link descriptions referred to "root" directory but that wasn't necessarily true
- Removes section about MSDN and TechNet
- Updates info about linking to Azure articles (no need to remove docs.microsoft.com since they're not on offline books)
> Update links article

- Contribute/how-to-write-use-markdown.md
External documentation update for the new code snippet Markdown extension and additional information about using Try .NET interactivity.
> update code Markdown extension and Try .NET

- Contribute/dotnet/dotnet-contribute.md
Fixes dotnet/docs#17297
We've updated our samples and snippets structure. This PR describes the new structure, and migration guidelines for existing snippets. In addition, rework the samples section to include the metadata necessary for the samples browser experience.
/cc @Thraka
> Rework .NET samples and snippets instructions

- Contribute/dotnet/dotnet-contribute.md
The how-to-contribute article hadn't been updated to reflect the closing of the community contributions GitHub project. Also removed some redundant content.
@gewarren @BillWagner Please review.
> Update contrib guide

- Contribute/docs-authoring/includes/image-extension.md
- Contribute/docs-authoring/includes/markdown-extension.md
Remove the now redundant EXT icon
/cc @Jim-Parker
> Remove now redundant ext icon

- Contribute/dotnet/dotnet-contribute.md
- Detailed the "shared" folder concept
- Removed
> "An accepted alternative structure contains one project per language that contains all snippets for all articles in that folder. This alternative has been used in the language reference areas because of very small snippets to demonstrate language syntax. It is discouraged in other areas."
We don't need this guidance anymore. Now that we have a "shared" folder, that's where snippets covered by this clause would go.
- Moved the **Example folder structure** section. This is now located after the **step: 5** area. It felt really strange being between **step 4** and **step 5**
- Removed
>"If you're creating samples as well as updating markdown, you'll need to create a separate PR for samples." I don't undestand this clause.
Samples are in a …
> Clean up clarify .NET contribute

- .github/workflows/check-build-warnings.yml
This GitHub Action turns the status checks section red (failure) if there are any build warnings. This helps to prevents PRs that introduce new build warnings from being merged. (But you can still merge the PR if you want. It doesn't block.)
This is what the status checks section will look like if there are build warnings:
> Add Action to check for build warnings

- Contribute/TOC.yml
- Contribute/index.md
- Contribute/metadata.md
The public contributor guide doesn't have any info about metadata. This article adds it.
cc @ievangelist
> Add metadata article

- Contribute/markdown-reference.md
Add/echo sentence that's in the internal contributor guide in the external contributor guide. In the public repos, we frequently see external contributors creating consecutive alerts in their pull requests. It would be good to have public style guidance to point to to steer them away from doing it (rather than saying "internal style guidance is to avoid . . ."). Thanks.
> align public CG with internal CG in re consecutive alerts

- Contribute/hacktoberfest.md
**Hi**, 
The Hacktoberfest Quality standard URL is not working, So I just removed the hyphen ( **quality-standards** ) to (**qualitystandards**).
> Fixed not found 404  Hacktoberfest Quality standard url

- .github/ISSUE_TEMPLATE/config.yml
Per these instructions: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> Remove ability to add a blank issue

- Contribute/TOC.yml
Removing article from the TOC but not archiving all together in case we want to use it next year.
> Remove Hacktoberfest from TOC

- Contribute/text-formatting-guidelines.md
Using `<kbd>` tags to identify keys is an accessibility issue; it enables screen readers to recognize references to keyboard keys.
> Use kbd HTML tags

- Contribute/how-to-write-links.md
Had public contributors getting confused about how linking to the .yml vs .md files work on our platform.  Added clarification.
-------
cc: @gewarren
> Add linking instructions for .yml + .md articles

- .github/ISSUE_TEMPLATE/general-issue-template.md
Updating the areas where feedback links appear in documentation and training on Microsoft Learn.
> Update general-issue-template for feedback links in documentation and training

- Contribute/how-to-write-workflows-major.md
It appears that the word "come" was left behind after a previous rewrite of a sentence: "If you want to ~~come~~ stop and return at a later time to make additional tweaks, that's OK!"
- Write to the PR reviewer in the PR comments: `@carlyrevier, @jehchow`
> Removed an extra word that caused confusion: come.

- Contribute/content/index.md
antecedent is "other advantages:".  It's not the repo.  Avoid generalization about open-source, sticking to the intention for Microsoft Docs.
> Correct grammar, avoid over-statement.

- Contribute/content/git-github-fundamentals.md
Tiny markdown fix: in one place the word articles had was surrounded by an inconsistent number of back-ticks (1 before and 2 afterwards). 
Fixed by surrounding it by 1 back-tick to match what was done earlier in the same sentence. Verified by looking at the 'preview' Windows
- If you have an open PR, tag the PR reviewers in comment with your question: …
> Tiny markdown fix for "articles" in git-github-fundamentals.md

- Contribute/content/dotnet/dotnet-contribute.md
The labels `good-first-issue` and `up-for-grabs` no longer exist. Instead, `good first issue` and `help wanted` exist.
Live link: https://learn.microsoft.com/en-us/contribute/content/dotnet/dotnet-contribute
> Fix outdated label references and links

- Contribute/content/how-to-write-links.md
> Update section on xref links

- Contribute/content/provide-feedback.md
This PR removes the list of repositories that are configured to use the `OpenSource` user feedback experience. We shouldn't publish a list like this for the following reasons:
- The current list is out of date and it's too hard to maintain the list.
- The configuration is at the docset level not the repo level. A repo can have multiple docsets.
- Within a docset, you can limit the `OpenSource` to specific folders. For example, the **dotnet/docs** repo uses `Standard` feedback for some folders and `OpenSource` for others.
- The customer doesn't know or care about which repos are configured. They only know what they see on the web page.
- If the `OpenSource` feedback control exists on the bottom of the page, then the user can use it. If its not there, then they can't. Knowing the repo name …
> Remove list of OpenSource repos

- Contribute/content/text-formatting-guidelines.md
> Update formatting guidelines

- Contribute/content/dotnet/api-documentation.md
> Add link to more info
